name: Daily Commit

# triggers: daily + manual
on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

permissions:
  contents: write   # allow pushes

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Create empty commit by 23f3004043@ds.study.iitm.ac.in
        run: |
          git config user.name "Daily Bot"
          git config user.email "23f3004043@ds.study.iitm.ac.in"
          git commit --allow-empty -m "Daily commit"
          git push origin main
