name: Daily Commit

on:
  schedule:
    - cron: "30 8 * * *"     # Runs daily at 08:30 UTC
  workflow_dispatch:         # Allows manual run

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create empty commit by 23f3004043@ds.study.iitm.ac.in
        run: |
          git config --global user.name "Daily Bot"
          git config --global user.email "23f3004043@ds.study.iitm.ac.in"
          git fetch origin
          git checkout main
          git commit --allow-empty -m "Daily commit"
          git push origin main
